#!/usr/bin/expect
if {$argc > 1} {
     log_user 0
     spawn ssh  [lrange $argv 0 0]
     expect {
        "yes/no" {
            send "yes\r"
            exp_continue
        }
        "assword:" {
            send "Dreamsk@3616\r"
            exp_continue
        }
        "++++++++++++++++" {}
    }
    set timeout 1
    expect "###"
    send "sudo su -\r"
    expect {
        "password" { send "Dreamsk@3616\r" }
    }
    send [lrange $argv 1 9]
    log_user 1
    send "\r"
    expect ".#" {}
    exit
}

if {$argc == 1} {
     spawn ssh  [lrange $argv 0 0]
     expect {
        "yes/no" {
            send "yes\r"
            exp_continue
        }
        "assword:" {
            send "Dreamsk@3616\r"
            exp_continue
        }
        "++++++++++++++++" {}
    }
    set timeout 1
    expect "###"
    send "sudo su -\r"
    expect {
        "password" { send "Dreamsk@3616\r" }
    }
    interact
}
