#!/usr/bin/expect
spawn ssh  [lrange $argv 0 0]

set timeout 1.4
expect {
    "(yes/no)?" { send "yes\r" ; exp_continue }
    "password:" { send "Dreamsk@3616\r" }
}

expect ".#"
send "sudo su -\r"
expect {
    "password" { send "Dreamsk@3616\r" }
}
#expect ".#"
#send_user "hello world!"
#send "\r"
interact
